notifications:
  email: false

dist: trusty
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8

language: c
compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -yq
  - chmod +x run_tests.sh

script:
  - ./run_tests.sh
