notifications:
  email: false
dist: trusty
sudo: required
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
install:
  - python setup.py install
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-faulthandler
script:
  - py.test algorithms -s -v -x --cov=./
after_success:
  - coveralls