notifications:
  email: false

dist: trusty
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8

language: c
compiler: gcc

before_install:
  - chmod +x run_tests.sh

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-8 /usr/bin/gcc
  - ./run_tests.sh
