notifications:
  email: false

dist: trusty
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7

language: c

before_install:
  - chmod +x run_tests.sh

script:
  - ./run_tests.sh
